apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: c3smonkey/template
          name: demo-service
          ports:
            - containerPort: 8080
              name: 8080-tcp
              protocol: TCP
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      restartPolicy: Always
